version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    container_name: "narociloservice"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=narocilo
  server:
    build: .
    container_name: "server"
    ports:
      - "8080:8080"
    depends_on:
      - postgres