kumuluzee:
  name: narocilo-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/narociloDS
      connection-url: jdbc:postgresql://narociloservice:5432/narocilo
      username: postgres
      password: postgres
      max-pool-size: 20