kumuluzee:
  name: narocilo-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
  datasources:
    - jndi-name: jdbc/narociloDS
      connection-url: jdbc:postgresql://narociloservice:5432/narocilo
      username: postgres
      password: postgres
      max-pool-size: 20
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="e83679ff-8e70-477a-85cb-b54b89a9ba98-ls.logit.io"
                                    port="10492" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'