INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 2, 'Cheeseburger', 10.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 2, 'Pizza Napolitana', 11.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 2, 'Pizza tuna', 10.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 2, 'Chilli con carne', 8.5);
INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 2, 'Tortilla z govedino', 9.5);
INSERT INTO narocilo (client, provider, items, cost) VALUES (1, 1, 'Cheeseburger, salad.', 10.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (2, 2, 'Fried chicken, baked potato.', 20.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (3, 3, 'Salami pizza.', 13.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (4, 4, 'Ribs, goulash.', 19.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (5, 1, 'Cheeseburger, curly fries.', 12.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (6, 2, 'Fried chicken, potato salad.', 19.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (2, 2, 'Fried chicken, baked potato.', 20.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (7, 4, 'Ribs, goulash, goulash.', 25.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (8, 5, 'Sushi rolls.', 16.0);
INSERT INTO narocilo (client, provider, items, cost) VALUES (2, 3, 'Zuccini pizza.', 12.0);